
#docker-version 17.06.2-ce

FROM ubuntu:14.04
MAINTAINER plusone lioa
RUN apt-get update -y  \
    && apt-get install curl  -y \
    && curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - \
    && apt-get install nodejs -y \
    && mkdir opt/app 
COPY ./src ./opt/app 

RUN cd opt/app \
    && npm install 
EXPOSE  3000
WORKDIR opt/app/
CMD [“node”,”start”]

